language: java
script:
  - mvn test
after_success:
  - npm install serverless -g
  - npm install serverless-domain-manager --save-dev
  - serverless create_domain
  - serverless deploy --conceal
branches:
  only:
    - master
    - prod
cache:
  timeout: 1000
  directories:
  - $HOME/.m2