# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service:
  name: LegendaryBotAPI # NOTE: update this with your service name
# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: java8
  stage: ${env:TRAVIS_BRANCH}
  apiKeys:
    - LegendaryBot-${self:provider.stage}
  environment:
    API_URL: ${self:custom.customDomain.domainName}
    DYNAMODB_TABLE_ITEM: LegendaryBot_item-${self:provider.stage}
    DYNAMODB_TABLE_DISCORD_USER: LegendaryBot_discordUser-${self:provider.stage}
    DYNAMODB_TABLE_DISCORD_GUILD: LegendaryBot_discordGuild-${self:provider.stage}
    DYNAMODB_TABLE_LEGENDARYCHECK: LegendaryBot_characterslc-${self:provider.stage}
    US_KEY: ${env:US_KEY_${self:provider.stage}}
    US_SECRET: ${env:US_SECRET_${self:provider.stage}}
    EU_KEY: ${env:EU_KEY_${self:provider.stage}}
    EU_SECRET: ${env:EU_SECRET_${self:provider.stage}}
    TWITTER_KEY: ${env:TWITTER_KEY}
    TWITTER_SECRET: ${env:TWITTER_SECRET}
    WARCRAFTLOGS_KEY: ${env:WARCRAFTLOGS_KEY}
    SENTRY_DSN: ${env:SENTRY_DSN}
    STATS_DIMENSION: ${self:provider.stage}
    SQS_QUEUE_NAME: LegendaryBot-LegendaryCheck-${self:provider.stage}
    SNS_LEGENDARYCHECK: LegendaryBot-LegendaryCheck-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cloudwatch:PutMetricData
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_ITEM}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_DISCORD_USER}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_DISCORD_GUILD}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_LEGENDARYCHECK}"
    - Effect: Allow
      Action:
        - sqs:GetQueueUrl
        - sqs:SendMessage
        - sqs:ListQueues
      Resource: "arn:aws:sqs:${opt:region, self:provider.region}:*:${self:provider.environment.SQS_QUEUE_NAME}"
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: { "Fn::Join" : [":", ["arn:aws:sns:${opt:region, self:provider.region}", { "Ref" : "AWS::AccountId" }, "${self:provider.environment.SNS_LEGENDARYCHECK}" ] ]  }
    - Effect: Allow
      Action:
        - SNS:ListTopics
      Resource: "*"
plugins:
  - serverless-domain-manager

package:
  artifact: target/legendarybotapi-dev.jar

functions:
  get-character:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSGetCharacterHandler
    timeout: 15
    events:
      - http:
          path: /character/{region}/{realm}/{character}
          method: get
  get-item:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSGetItemHandler
    timeout: 15
    events:
      - http:
          path: /item/{region}/{id}
          method: get
  get-lasttweet:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSGetLastTweetHandler
    timeout: 15
    events:
      - http:
          path: /twitter/{region}
          method: get
  get-legion-building:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSGetLegionBuildingHandler
    timeout: 15
    events:
      - http:
          path: /region/{region}/legionbuilding
          method: get
  get-discord-user-main-character:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSGetDiscordUserMainCharacter
    timeout: 15
    events:
      - http:
          path: /user/{userId}/character/{guildId}
          method: get
  get-discord-user-all-character:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSGetGuildCharactersForUser
    timeout: 15
    events:
      - http:
          path: /user/{userId}/character/all/{guildName}
          method: get
  set-discord-user-main-character:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSSetDiscordUserMainCharacter
    timeout: 15
    events:
      - http:
          path: /user/{userId}/character/{guildId}/{region}/{realm}/{character}
          method: post
          private: true
  set-raw-character:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSSetRawCharacter
    timeout: 30
    events:
      - http:
          path: /user/rawCharacter
          method: post
          private: true
  get-auth-battlenet:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSGetOAuthLoginLink
    timeout: 15
    events:
      - http:
          path: /oauth/login/{region}/{id}
          method: get
  get-auth-battlenetcallback:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSGetBattleNetCallback
    timeout: 30
    events:
      - http:
          path: /oauth/battlenetcallback
          method: get
  get-guild-setting:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSGetDiscordGuildSetting
    timeout: 15
    events:
      - http:
          path: /guild/{guildId}/setting/{key}
          method: get
          private: true
  set-guild-setting:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSSetDiscordGuildSetting
    timeout: 15
    events:
      - http:
          path: /guild/{guildId}/setting/{key}
          method: post
          private: true
  set-guild-setting-raw:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSSetDiscordGuildSettingRaw
    timeout: 15
    events:
      - http:
          path: /guild/{guildId}/settingRaw
          method: post
          private: true
  delete-guild-setting:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSDeleteDiscordGuildSetting
    timeout: 15
    events:
      - http:
          path: /guild/{guildId}/setting/{key}
          method: delete
          private: true
  get-guild-rank-update:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSGetDiscordGuildRankUpdate
    timeout: 30
    events:
      - http:
          path: /guild/{guildId}/rankUpdate
          method: post
          private: true
  get-realm-status:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSGetRealmStatus
    timeout: 15
    events:
      - http:
          path: /server/{region}/{realm}/status
          method: get
  get-guild-latest-log:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSGetGuildLatestLog
    timeout: 15
    events:
      - http:
          path: /guild/{guildId}/getLatestLog
          method: get
  add-stats-point:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSAddStatsPoint
    timeout: 15
    events:
      - http:
          path: /stats
          method: post
          private: true
  get-overwatch-stats:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSGetOverwatchStats
    timeout: 15
    events:
      - http:
          path: /overwatch/{region}/{battletag}
          method: get
  get-guild-raid-rank:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSGetGuildRaidRank
    timeout: 15
    events:
      - http:
          path: /guild/{guildId}/rank
          method: get
  get-region-token-price:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSGetTokenPrice
    events:
      - http:
          path: /region/{region}/wowtoken
          method: get
  handle-legendary-check:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSHandleLegendaryCheck
    timeout: 300
    events:
      - sns: ${self:provider.environment.SNS_LEGENDARYCHECK}
  schedule-legendary-check:
    handler: com.greatmancode.legendarybotapi.impl.aws.AWSScheduleLegendaryCheck
    timeout: 120
    events:
      - schedule: rate(30 minutes)

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE_ITEM}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
    DynamoDbTable1:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE_DISCORD_USER}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
    DynamoDbTableGuild:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE_DISCORD_GUILD}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
    DynamoDbTablecharacterslc:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE_LEGENDARYCHECK}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
    LegendaryCheckSQS:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.environment.SQS_QUEUE_NAME}


custom:
  domains:
    prod: api.legendarybot.info
    master: api-dev.legendarybot.info
  customDomain:
    domainName: ${self:custom.domains.${self:provider.stage}}
    basePath: api
    createRoute53Record: false
    endpointType: 'edge'